### ISSUE TITLE
prevent re-adding listeners on each render

### ISSUE THREAD

**Issue by chpio** [d4rekanguok/use-zone-breakpoints#5]
a dynamic object

https://github.com/d4rekanguok/use-zone-breakpoints/blob/6fd5edc8256118c473e6229f4910dd90c8262e41/src/index.tsx#L37

is used as a dependency for `useEffect`

https://github.com/d4rekanguok/use-zone-breakpoints/blob/6fd5edc8256118c473e6229f4910dd90c8262e41/src/index.tsx#L57

----

using `bps` as the whole dependency array should do the job?

```js
useEffect(() => {}, bps);
```

**Comment by d4rekanguok** [comment]
Thank you for this & also the edit suggestion! I will give it a try.
